#!/usr/bin/env bun

import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join } from "node:path";

type DeclarationTarget = {
  sourcePath: string;
  outputPath: string;
  exportName: string;
  label: string;
  tempPrefix: string;
};

const projectRoot = join(import.meta.dir, "..");
const generatedDir = join(projectRoot, "generated");

const targets: DeclarationTarget[] = [
  {
    sourcePath: join(projectRoot, "src", "bun", "execute-typescript-api-contract.ts"),
    outputPath: join(generatedDir, "execute-typescript-api.generated.ts"),
    exportName: "EXECUTE_TYPESCRIPT_API_DECLARATION",
    label: "execute_typescript API",
    tempPrefix: "svvy-execute-typescript-api-",
  },
  {
    sourcePath: join(
      projectRoot,
      "src",
      "bun",
      "smithers-runtime",
      "workflow-authoring-contract.ts",
    ),
    outputPath: join(generatedDir, "workflow-authoring-contract.generated.ts"),
    exportName: "WORKFLOW_AUTHORING_CONTRACT_DECLARATION",
    label: "workflow authoring contract",
    tempPrefix: "svvy-workflow-authoring-contract-",
  },
];

function resolveTsgoPath(): string {
  const fromPath = Bun.which("tsgo");
  if (fromPath) {
    return fromPath;
  }

  const bundledPath = join(projectRoot, "node_modules", ".bin", "tsgo");
  if (existsSync(bundledPath)) {
    return bundledPath;
  }

  throw new Error("Could not find the tsgo executable. Run `bun install` first.");
}

function emitDeclaration(target: DeclarationTarget): string {
  const sourceDir = dirname(target.sourcePath);
  const tempDir = mkdtempSync(join(tmpdir(), target.tempPrefix));
  const outDir = join(tempDir, "out");
  const configPath = join(tempDir, "tsconfig.json");
  const emittedPath = join(outDir, `${basename(target.sourcePath, ".ts")}.d.ts`);

  try {
    const tsconfig = {
      compilerOptions: {
        target: "ES2022",
        module: "ESNext",
        moduleResolution: "bundler",
        allowImportingTsExtensions: true,
        declaration: true,
        emitDeclarationOnly: true,
        removeComments: false,
        skipLibCheck: true,
        strict: true,
        types: [],
        rootDir: sourceDir,
        outDir: "./out",
      },
      files: [target.sourcePath],
    };
    writeFileSync(configPath, `${JSON.stringify(tsconfig, null, 2)}\n`, "utf8");

    const result = Bun.spawnSync({
      cmd: [resolveTsgoPath(), "-p", configPath],
      cwd: projectRoot,
      stdout: "pipe",
      stderr: "pipe",
      env: process.env,
    });
    const stdout = Buffer.from(result.stdout).toString("utf8").trim();
    const stderr = Buffer.from(result.stderr).toString("utf8").trim();
    if (result.exitCode !== 0) {
      const output = [stderr, stdout].filter(Boolean).join("\n");
      throw new Error(`Failed to generate ${target.label} declaration with tsgo.\n${output}`);
    }

    const emittedDeclaration = readFileSync(emittedPath, "utf8");
    if (!emittedDeclaration.trim()) {
      throw new Error(`TypeScript skipped declaration emit for ${target.label}.`);
    }

    return emittedDeclaration;
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

function toAmbientDeclaration(source: string): string {
  return source
    .replace(/^export\s+\{\};\s*$/gm, "")
    .replace(/^export\s+/gm, "")
    .trim()
    .concat("\n");
}

function writeIfChanged(filePath: string, nextContent: string): boolean {
  const previous = (() => {
    try {
      return readFileSync(filePath, "utf8");
    } catch {
      return null;
    }
  })();

  if (previous === nextContent) {
    return false;
  }

  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, nextContent, "utf8");
  return true;
}

let changedCount = 0;

for (const target of targets) {
  const emittedDeclaration = emitDeclaration(target);
  const ambientDeclaration = toAmbientDeclaration(emittedDeclaration);
  const moduleFileContents = [
    "// This file is generated by scripts/generate-api-declarations.ts.",
    `// Do not edit it by hand; update ${target.sourcePath.slice(projectRoot.length + 1)} instead.`,
    "",
    `export const ${target.exportName} = ${JSON.stringify(ambientDeclaration)};`,
    "",
  ].join("\n");

  if (writeIfChanged(target.outputPath, moduleFileContents)) {
    changedCount += 1;
    console.log(`Generated ${target.label} declaration assets.`);
  } else {
    console.log(`${target.label} declaration assets are up to date.`);
  }
}

if (changedCount > 0) {
  console.log(`Generated ${changedCount} API declaration module(s).`);
}
