#!/usr/bin/env bun

import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join } from "node:path";

const projectRoot = join(import.meta.dir, "..");
const sourcePath = join(projectRoot, "src", "bun", "execute-typescript-api-contract.ts");
const generatedDir = join(projectRoot, "generated");
const moduleOutputPath = join(generatedDir, "execute-typescript-api.generated.ts");

function resolveTsgoPath(): string {
  const fromPath = Bun.which("tsgo");
  if (fromPath) {
    return fromPath;
  }

  const bundledPath = join(projectRoot, "node_modules", ".bin", "tsgo");
  if (existsSync(bundledPath)) {
    return bundledPath;
  }

  throw new Error("Could not find the tsgo executable. Run `bun install` first.");
}

function emitDeclaration(sourceFilePath: string): string {
  const sourceDir = dirname(sourceFilePath);
  const tempDir = mkdtempSync(join(tmpdir(), "svvy-execute-typescript-api-"));
  const outDir = join(tempDir, "out");
  const configPath = join(tempDir, "tsconfig.json");
  const emittedPath = join(outDir, `${basename(sourceFilePath, ".ts")}.d.ts`);

  try {
    const tsconfig = {
      compilerOptions: {
        target: "ES2022",
        module: "ESNext",
        moduleResolution: "bundler",
        allowImportingTsExtensions: true,
        declaration: true,
        emitDeclarationOnly: true,
        removeComments: false,
        skipLibCheck: true,
        strict: true,
        types: [],
        rootDir: sourceDir,
        outDir: "./out",
      },
      files: [sourceFilePath],
    };
    writeFileSync(configPath, `${JSON.stringify(tsconfig, null, 2)}\n`, "utf8");

    const result = Bun.spawnSync({
      cmd: [resolveTsgoPath(), "-p", configPath],
      cwd: projectRoot,
      stdout: "pipe",
      stderr: "pipe",
      env: process.env,
    });
    const stdout = Buffer.from(result.stdout).toString("utf8").trim();
    const stderr = Buffer.from(result.stderr).toString("utf8").trim();
    if (result.exitCode !== 0) {
      const output = [stderr, stdout].filter(Boolean).join("\n");
      throw new Error(
        `Failed to generate execute_typescript API declaration with tsgo.\n${output}`,
      );
    }

    const emittedDeclaration = readFileSync(emittedPath, "utf8");
    if (!emittedDeclaration.trim()) {
      throw new Error("TypeScript skipped declaration emit for execute_typescript API contract.");
    }

    return emittedDeclaration;
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

function toAmbientDeclaration(source: string): string {
  return source
    .replace(/^export\s+\{\};\s*$/gm, "")
    .replace(/^export\s+/gm, "")
    .trim()
    .concat("\n");
}

function writeIfChanged(filePath: string, nextContent: string): boolean {
  const previous = (() => {
    try {
      return readFileSync(filePath, "utf8");
    } catch {
      return null;
    }
  })();

  if (previous === nextContent) {
    return false;
  }

  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, nextContent, "utf8");
  return true;
}

const emittedDeclaration = emitDeclaration(sourcePath);
const ambientDeclaration = toAmbientDeclaration(emittedDeclaration);
const moduleFileContents = [
  "// This file is generated by scripts/generate-execute-typescript-api.ts.",
  "// Do not edit it by hand; update src/bun/execute-typescript-api-contract.ts instead.",
  "",
  `export const EXECUTE_TYPESCRIPT_API_DECLARATION = ${JSON.stringify(ambientDeclaration)};`,
  "",
].join("\n");

const changedModule = writeIfChanged(moduleOutputPath, moduleFileContents);

if (changedModule) {
  console.log("Generated execute_typescript API declaration assets.");
} else {
  console.log("execute_typescript API declaration assets are up to date.");
}
