#!/usr/bin/env bun

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import * as ts from "typescript";

const projectRoot = join(import.meta.dir, "..");
const sourcePath = join(projectRoot, "src", "bun", "execute-typescript-api-contract.ts");
const generatedDir = join(projectRoot, "src", "bun", "generated");
const declarationOutputPath = join(generatedDir, "execute-typescript-api.generated.d.ts");
const moduleOutputPath = join(generatedDir, "execute-typescript-api.generated.ts");

function formatDiagnostics(diagnostics: readonly ts.Diagnostic[]): string {
  return diagnostics
    .map((diagnostic) => {
      const message = ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n");
      if (!diagnostic.file || diagnostic.start === undefined) {
        return message;
      }
      const position = diagnostic.file.getLineAndCharacterOfPosition(diagnostic.start);
      return `${diagnostic.file.fileName}:${position.line + 1}:${position.character + 1} ${message}`;
    })
    .join("\n");
}

function emitDeclaration(sourceFilePath: string): string {
  const compilerOptions: ts.CompilerOptions = {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    declaration: true,
    emitDeclarationOnly: true,
    removeComments: false,
    skipLibCheck: true,
    strict: true,
  };

  let emittedDeclaration = "";
  const host = ts.createCompilerHost(compilerOptions, true);
  const originalWriteFile = host.writeFile.bind(host);
  host.writeFile = (fileName, text, ...rest) => {
    if (fileName.endsWith(".d.ts")) {
      emittedDeclaration = text;
      return;
    }
    originalWriteFile(fileName, text, ...rest);
  };

  const program = ts.createProgram([sourceFilePath], compilerOptions, host);
  const diagnostics = ts.getPreEmitDiagnostics(program);
  if (diagnostics.length > 0) {
    throw new Error(
      `Failed to generate execute_typescript API declaration.\n${formatDiagnostics(diagnostics)}`,
    );
  }

  const result = program.emit();
  if (result.emitSkipped || !emittedDeclaration.trim()) {
    throw new Error("TypeScript skipped declaration emit for execute_typescript API contract.");
  }

  return emittedDeclaration;
}

function toAmbientDeclaration(source: string): string {
  return source
    .replace(/^export\s+\{\};\s*$/gm, "")
    .replace(/^export\s+/gm, "")
    .trim()
    .concat("\n");
}

function writeIfChanged(filePath: string, nextContent: string): boolean {
  const previous = (() => {
    try {
      return readFileSync(filePath, "utf8");
    } catch {
      return null;
    }
  })();

  if (previous === nextContent) {
    return false;
  }

  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, nextContent, "utf8");
  return true;
}

const emittedDeclaration = emitDeclaration(sourcePath);
const ambientDeclaration = toAmbientDeclaration(emittedDeclaration);
const declarationFileContents = [
  "// This file is generated by scripts/generate-execute-typescript-api.ts.",
  "// Do not edit it by hand; update src/bun/execute-typescript-api-contract.ts instead.",
  "",
  ambientDeclaration.trimEnd(),
  "",
].join("\n");
const moduleFileContents = [
  "// This file is generated by scripts/generate-execute-typescript-api.ts.",
  "// Do not edit it by hand; update src/bun/execute-typescript-api-contract.ts instead.",
  "",
  `export const EXECUTE_TYPESCRIPT_API_DECLARATION = ${JSON.stringify(ambientDeclaration)};`,
  "",
].join("\n");

const changedDeclaration = writeIfChanged(declarationOutputPath, declarationFileContents);
const changedModule = writeIfChanged(moduleOutputPath, moduleFileContents);

if (changedDeclaration || changedModule) {
  console.log("Generated execute_typescript API declaration assets.");
} else {
  console.log("execute_typescript API declaration assets are up to date.");
}
