import { SMITHERS_MEMORY_INSTRUCTIONS } from "../../../generated/smithers-instructions.generated";

export const SMITHERS_SVVY_BOUNDARY_APPENDIX = [
  "svvy Smithers boundary for handler threads:",
  "",
  "Work in the workspace `.smithers/` package. Use the checked `smithers` CLI binary through Shell. TypeScript Smithers source still imports from `smithers-orchestrator`.",
  "Import reusable svvy workflow material from `@svvy/workflows` when it exists and matches the task.",
  "Use `svvyx workflows models list --json` when choosing provider/model/reasoning values for saved workflow agents or reusable task-agent parameters.",
  "Use `svvyx workflows save` only when promoting reusable material to the app-global Workflows source library.",
  "Generated Workflows output is read-only; edit source and rebuild.",
].join("\n");

const HANDLER_WORKFLOW_AUTHORING_GUIDE_LINES = [
  "Workflow authoring guide for handler threads:",
  "",
  "Decision flow:",
  "- Use direct tools for bounded work that does not need workflow supervision, pause/resume, fan-out, or reusable structured outputs.",
  "- Use the checked `smithers` CLI binary through Shell for workflow initialization, execution, process inspection, and run inspection.",
  "- Author workspace-local Smithers source under `.smithers/` when the delegated task needs a concrete workflow.",
  "- Inspect app-global reusable workflow source with `svvyx workflows list` only when reusable source-library context is relevant.",
  "- Import reusable values from `@svvy/workflows` when they exist and match the task.",
  "- Save or build app-global reusable workflow source with `svvyx workflows save` or `svvyx workflows build` only when the user explicitly asks for reusable workflow-library assets.",
  "",
  "Smithers model:",
  "- A workflow is a React/JSX tree rendered by createSmithers(...).",
  "- A render mounts Tasks and control-flow nodes; ready Tasks run, write Zod-validated outputs, and Smithers renders again from persisted state.",
  "- Put durable data in Task outputs. Keep task ids stable and derived from the job, not timestamps or array indexes.",
  "- Parse workflow input explicitly before using it inside the workflow.",
  "- Run, resume, approve, and inspect workflows with the official Smithers CLI. Do not invent svvy workflow wrapper calls.",
].join("\n");

const MINIMAL_ARTIFACT_WORKFLOW_EXAMPLE = [
  "Example: minimal workspace-local Smithers workflow",
  "```ts",
  'import React from "react";',
  'import { createSmithers } from "smithers-orchestrator";',
  'import { z } from "zod";',
  "",
  "const inputSchema = z.object({ objective: z.string().min(1) });",
  "const noteSchema = z.object({ note: z.string().min(1) });",
  "",
  "const smithersApi = createSmithers({ input: inputSchema, note: noteSchema });",
  "",
  "export default smithersApi.smithers((ctx) => {",
  "  const launch = inputSchema.parse(ctx.input);",
  "  return React.createElement(",
  "    smithersApi.Workflow,",
  '    { name: "objective-note" },',
  "    React.createElement(smithersApi.Task, {",
  '      id: "prepare_note",',
  "      output: smithersApi.outputs.note,",
  "      children: { note: `Objective: ${launch.objective}` },",
  "    }),",
  "  );",
  "});",
  "```",
  'Run reusable or seeded workflows with the checked Smithers CLI, for example `smithers workflow run implement --prompt "..."`. For direct TSX files, use the current file-run form from the generated Smithers docs after upstream command examples have been rewritten to `smithers`.',
].join("\n");

const PARALLEL_WORKFLOW_EXAMPLE = [
  "Example: parallel fan-out with synthesis",
  "```ts",
  "const findingSchema = z.object({ reviewer: z.string(), summary: z.string() });",
  "const synthesisSchema = z.object({ summary: z.string(), findings: z.array(findingSchema) });",
  "",
  "const inputSchema = z.object({ objective: z.string().min(1) });",
  "const smithersApi = createSmithers({ input: inputSchema, finding: findingSchema, synthesis: synthesisSchema });",
  "",
  "export default smithersApi.smithers((ctx) => {",
  "  const launch = inputSchema.parse(ctx.input);",
  "  const findings = ctx.outputs.finding ?? [];",
  "  return React.createElement(",
  "    smithersApi.Workflow,",
  '    { name: "parallel-review" },',
  "    React.createElement(",
  "      smithersApi.Sequence,",
  "      null,",
  "      React.createElement(",
  "        smithersApi.Parallel,",
  "        null,",
  "        React.createElement(smithersApi.Task, { id: 'review_correctness', output: smithersApi.outputs.finding, children: { reviewer: 'correctness', summary: launch.objective } }),",
  "        React.createElement(smithersApi.Task, { id: 'review_tests', output: smithersApi.outputs.finding, children: { reviewer: 'tests', summary: launch.objective } }),",
  "      ),",
  "      React.createElement(smithersApi.Task, {",
  "        id: 'synthesis',",
  "        output: smithersApi.outputs.synthesis,",
  "        children: { summary: `Synthesized ${findings.length} findings.`, findings },",
  "      }),",
  "    ),",
  "  );",
  "});",
  "```",
].join("\n");

const ASSET_AND_AGENT_EXAMPLE = [
  "Example: inspect reusable app-global workflow source before deciding",
  "```sh",
  "svvyx workflows list --json",
  "svvyx workflows models list --json",
  "```",
  "",
  "Example: write reusable app-global workflow agent parameters only when the user wants reusable agents",
  "```ts",
  'import { Agents } from "@svvy/workflows";',
  "",
  "export const reviewerAgent = Agents.defineTaskAgent({",
  "  id: 'reviewer',",
  "  label: 'Reviewer',",
  "  provider: 'openai',",
  "  model: 'gpt-5.4',",
  "  reasoningEffort: 'medium',",
  "  instructions: 'Review the task result for correctness, edge cases, and test coverage.',",
  "  overrides: { cx: 'loaded' },",
  "});",
  "```",
].join("\n");

const TASK_AGENT_EXAMPLE = [
  "Example: use reusable task-agent parameters in a task",
  "```ts",
  'import { Agents } from "@svvy/workflows";',
  "",
  "const reviewerAgent = Agents.defineTaskAgent(Agents.reviewerAgent);",
  "",
  "React.createElement(smithersApi.Task, {",
  "  id: 'review',",
  "  output: smithersApi.outputs.reviewResult,",
  "  agent: reviewerAgent,",
  "  children: 'Review the implementation and return the requested schema.',",
  "});",
  "```",
  "",
  "Example: define task-agent parameters directly when the workflow owns the task-agent configuration",
  "```ts",
  'import { Agents } from "@svvy/workflows";',
  "",
  "const explorerAgent = Agents.defineTaskAgent({",
  "  id: 'explore',",
  "  label: 'Explorer',",
  "  provider: 'openai',",
  "  model: 'gpt-5.4',",
  "  reasoningEffort: 'medium',",
  "  instructions: 'Explore the requested area and return concise findings.',",
  "});",
  "",
  "React.createElement(smithersApi.Task, {",
  "  id: 'explore',",
  "  output: smithersApi.outputs.finding,",
  "  agent: explorerAgent,",
  "  children: 'Map the relevant code paths.',",
  "});",
  "```",
].join("\n");

export const HANDLER_WORKFLOW_AUTHORING_APPENDIX = [
  HANDLER_WORKFLOW_AUTHORING_GUIDE_LINES,
  "",
  MINIMAL_ARTIFACT_WORKFLOW_EXAMPLE,
  "",
  PARALLEL_WORKFLOW_EXAMPLE,
  "",
  ASSET_AND_AGENT_EXAMPLE,
  "",
  TASK_AGENT_EXAMPLE,
].join("\n");

export const SMITHERS_MEMORY_FRAGMENT = SMITHERS_MEMORY_INSTRUCTIONS;
