const HANDLER_WORKFLOW_AUTHORING_GUIDE_LINES = [
  "Workflow authoring guide for handler threads:",
  "",
  "Use the generated workflow-authoring contract above for exact TypeScript shapes. Use the generated execute_typescript SDK below for exact api.* shapes.",
  "",
  "Decision flow:",
  "- Use direct execute_typescript for bounded work that does not need workflow supervision, pause/resume, fan-out, or reusable structured outputs.",
  "- Inspect runnable entries with smithers.list_workflows before authoring anything new.",
  "- Inspect reusable definitions, prompts, components, and agent-profile components with api.workflow.listAssets(...) inside execute_typescript, then read promising files with api.repo.readFile(...).",
  "- Reuse a saved runnable entry when it clearly fits.",
  "- Otherwise author a short-lived artifact workflow under .svvy/artifacts/workflows/<artifact_workflow_id>/.",
  "- Write reusable saved workflow assets under .svvy/workflows/... only when the user explicitly asks for reusable pieces to be saved.",
  "",
  "Smithers model:",
  "- A workflow is a React/JSX tree rendered by createSmithers(...).",
  "- A render mounts Tasks and control-flow nodes; ready Tasks run, write Zod-validated outputs, and Smithers renders again from persisted state.",
  "- Put durable data in Task outputs. Keep task ids stable and derived from the job, not timestamps or array indexes.",
  "- svvy validates launchSchema before smithers.run_workflow starts the run; inside the workflow, parse ctx.input with the same launchSchema.",
  "- Use a permissive Smithers input schema in authored workflows so entries can share the workspace runtime database while each entry keeps its own launchSchema contract.",
].join("\n");

const MINIMAL_ARTIFACT_WORKFLOW_EXAMPLE = [
  "Example: minimal artifact runnable entry",
  "```ts",
  'import React from "react";',
  'import { createSmithers } from "smithers-orchestrator";',
  'import { z } from "zod";',
  "",
  "const runtimeInputSchema = z.object({}).passthrough();",
  "export const launchSchema = z.object({ objective: z.string().min(1) });",
  "const noteSchema = z.object({ note: z.string().min(1) });",
  'const resultSchema = z.object({ status: z.enum(["completed", "blocked"]), summary: z.string().min(1) });',
  "",
  'export const workflowId = "artifact_objective_note";',
  'export const label = "Artifact Objective Note";',
  'export const summary = "Creates a structured note for one delegated objective."; ',
  "export const definitionPaths = [] as const;",
  "export const promptPaths = [] as const;",
  "export const componentPaths = [] as const;",
  "",
  "export function createRunnableEntry(input: { dbPath: string }) {",
  "  const smithersApi = createSmithers(",
  "    { input: runtimeInputSchema, note: noteSchema, result: resultSchema },",
  "    { dbPath: input.dbPath },",
  "  );",
  "",
  "  return {",
  "    workflowId,",
  '    workflowSource: "artifact" as const,',
  "    launchSchema,",
  "    resultSchema,",
  "    workflow: smithersApi.smithers((ctx) => {",
  "      const launch = launchSchema.parse(ctx.input);",
  "      const note = ctx.outputs.note?.at(-1);",
  "      return React.createElement(",
  "        smithersApi.Workflow,",
  '        { name: "artifact-objective-note" },',
  "        React.createElement(",
  "          smithersApi.Sequence,",
  "          null,",
  "          React.createElement(smithersApi.Task, {",
  '            id: "prepare_note",',
  "            output: smithersApi.outputs.note,",
  "            children: { note: `Objective: ${launch.objective}` },",
  "          }),",
  "          React.createElement(smithersApi.Task, {",
  '            id: "result",',
  "            output: smithersApi.outputs.result,",
  "            children: {",
  '              status: "completed",',
  "              summary: note?.note ?? `Objective: ${launch.objective}`,",
  "            },",
  "          }),",
  "        ),",
  "      );",
  "    }),",
  "  };",
  "}",
  "```",
].join("\n");

const PARALLEL_WORKFLOW_EXAMPLE = [
  "Example: parallel fan-out with synthesis",
  "```ts",
  "const findingSchema = z.object({ reviewer: z.string(), summary: z.string() });",
  "const synthesisSchema = z.object({ summary: z.string(), findings: z.array(findingSchema) });",
  "",
  "const smithersApi = createSmithers(",
  "  { input: runtimeInputSchema, finding: findingSchema, synthesis: synthesisSchema },",
  "  { dbPath: input.dbPath },",
  ");",
  "",
  "workflow: smithersApi.smithers((ctx) => {",
  "  const launch = launchSchema.parse(ctx.input);",
  "  const findings = ctx.outputs.finding ?? [];",
  "  return React.createElement(",
  "    smithersApi.Workflow,",
  '    { name: "parallel-review" },',
  "    React.createElement(",
  "      smithersApi.Sequence,",
  "      null,",
  "      React.createElement(",
  "        smithersApi.Parallel,",
  "        null,",
  "        React.createElement(smithersApi.Task, { id: 'review_correctness', output: smithersApi.outputs.finding, children: { reviewer: 'correctness', summary: launch.objective } }),",
  "        React.createElement(smithersApi.Task, { id: 'review_tests', output: smithersApi.outputs.finding, children: { reviewer: 'tests', summary: launch.objective } }),",
  "      ),",
  "      React.createElement(smithersApi.Task, {",
  "        id: 'synthesis',",
  "        output: smithersApi.outputs.synthesis,",
  "        children: { summary: `Synthesized ${findings.length} findings.`, findings },",
  "      }),",
  "    ),",
  "  );",
  "})",
  "```",
].join("\n");

const ASSET_AND_PROFILE_EXAMPLE = [
  "Example: discover assets and write an agent-profile component",
  "```ts",
  "const definitions = await api.workflow.listAssets({ kind: 'definition', scope: 'saved' });",
  "const profiles = await api.workflow.listAssets({ kind: 'component', subtype: 'agent-profile', scope: 'saved' });",
  "const profileSource = profiles[0] ? await api.repo.readFile({ path: profiles[0].path }) : null;",
  "const models = profiles.length === 0 ? await api.workflow.listModels() : [];",
  "return { definitionIds: definitions.map((asset) => asset.id), profileSource, models };",
  "```",
  "",
  "```ts",
  "await api.repo.writeFile({",
  "  path: '.svvy/workflows/components/reviewer-profile.ts',",
  "  createDirectories: true,",
  "  text: `/**",
  " * @svvyAssetKind component",
  " * @svvySubtype agent-profile",
  " * @svvyId reviewer_profile",
  " * @svvyTitle Reviewer Profile",
  " * @svvySummary Reusable reviewer profile for workflow tasks.",
  " * @svvyTags review",
  " * @svvyExports reviewerProfile",
  " * @svvyProviderModelSummary openai/gpt-5.4",
  " * @svvyToolsetSummary execute_typescript",
  " */",
  "export const reviewerProfile = {",
  "  provider: 'openai',",
  "  model: 'gpt-5.4',",
  "  thinkingLevel: 'medium',",
  "  systemPrompt: 'Review the task result for correctness, edge cases, and test coverage.',",
  "  toolSurface: ['execute_typescript'] as const,",
  "};",
  "`,",
  "});",
  "```",
].join("\n");

const AGENTLIKE_TASK_EXAMPLE = [
  "Example: use AgentLike in a task",
  "```ts",
  'import type { AgentLike } from "smithers-orchestrator";',
  "",
  "const reviewerAgent: AgentLike = {",
  '  id: "reviewer-agent",',
  "  async generate(rawArgs: unknown) {",
  "    const args = rawArgs as { prompt?: string };",
  "    return {",
  "      text: JSON.stringify({ status: 'completed', summary: args.prompt ?? 'Reviewed.' }),",
  "      usage: { inputTokens: 0, outputTokens: 0, totalTokens: 0 },",
  "    };",
  "  },",
  "};",
  "",
  "React.createElement(smithersApi.Task, {",
  "  id: 'review',",
  "  output: smithersApi.outputs.reviewResult,",
  "  agent: reviewerAgent,",
  "  children: 'Review the implementation and return the requested schema.',",
  "});",
  "```",
].join("\n");

export const HANDLER_WORKFLOW_AUTHORING_APPENDIX = [
  HANDLER_WORKFLOW_AUTHORING_GUIDE_LINES,
  "",
  MINIMAL_ARTIFACT_WORKFLOW_EXAMPLE,
  "",
  PARALLEL_WORKFLOW_EXAMPLE,
  "",
  ASSET_AND_PROFILE_EXAMPLE,
  "",
  AGENTLIKE_TASK_EXAMPLE,
].join("\n");
