export type AdoptedEffectRuntimeModuleExport = {
  readonly module: string;
  readonly members: readonly string[];
};

export const adoptedEffectRuntimeModuleExports = [
  { module: "@effect/platform-bun/BunCrypto", members: ["layer"] },
  { module: "@effect/platform-bun/BunFileSystem", members: ["layer"] },
  { module: "@effect/platform-bun/BunPath", members: ["layer"] },
  {
    module: "effect/Cause",
    members: [
      "hasInterruptsOnly",
      "isDieReason",
      "isFailReason",
      "isInterruptReason",
      "pretty",
      "squash",
    ],
  },
  { module: "effect/Config", members: ["ConfigError", "all", "int", "mapOrFail", "withDefault"] },
  { module: "effect/Context", members: ["Service", "getOption"] },
  { module: "effect/DateTime", members: ["formatIso", "now"] },
  { module: "effect/Deferred", members: ["await", "fail", "make", "succeed"] },
  {
    module: "effect/Effect",
    members: [
      "acquireRelease",
      "addFinalizer",
      "all",
      "andThen",
      "as",
      "asVoid",
      "catch",
      "catchCause",
      "clockWith",
      "contextWith",
      "die",
      "ensuring",
      "fail",
      "failCause",
      "flatMap",
      "fn",
      "forEach",
      "forkIn",
      "gen",
      "ignore",
      "map",
      "mapError",
      "matchEffect",
      "onError",
      "promise",
      "provide",
      "provideService",
      "runPromise",
      "runSync",
      "sleep",
      "succeed",
      "suspend",
      "sync",
      "tap",
      "try",
      "tryPromise",
      "void",
    ],
  },
  { module: "effect/Exit", members: ["isFailure", "isSuccess", "match", "succeed", "void"] },
  { module: "effect/FileSystem", members: ["FileSystem"] },
  { module: "effect/Layer", members: ["effect", "mergeAll", "provide", "succeed"] },
  { module: "effect/ManagedRuntime", members: ["make"] },
  { module: "effect/Option", members: ["isNone", "some"] },
  { module: "effect/Path", members: ["Path"] },
  { module: "effect/Queue", members: ["dropping", "offer", "shutdown"] },
  { module: "effect/Ref", members: ["get", "getAndSet", "make", "modify", "update"] },
  {
    module: "effect/Schema",
    members: [
      "Array",
      "Boolean",
      "DateTimeUtcFromString",
      "Defect",
      "Json",
      "Literal",
      "Literals",
      "Null",
      "NullOr",
      "Number",
      "Record",
      "Redacted",
      "SchemaError",
      "String",
      "Struct",
      "TaggedErrorClass",
      "TemplateLiteral",
      "Union",
      "Unknown",
      "brand",
      "check",
      "decodeUnknownEffect",
      "decodeUnknownExit",
      "decodeUnknownSync",
      "encodeEffect",
      "encodeExit",
      "encodeUnknownSync",
      "isFinite",
      "isGreaterThan",
      "isGreaterThanOrEqualTo",
      "isInt",
      "isLengthBetween",
      "isLessThanOrEqualTo",
      "isNonEmpty",
      "isPattern",
      "makeFilter",
      "optionalKey",
      "refine",
      "withDecodingDefaultKey",
    ],
  },
  { module: "effect/SchemaIssue", members: ["InvalidValue", "makeFormatterStandardSchemaV1"] },
  {
    module: "effect/Scope",
    members: ["Scope", "addFinalizer", "close", "fork", "make", "makeUnsafe"],
  },
  { module: "effect/Semaphore", members: ["make"] },
  {
    module: "effect/Stream",
    members: [
      "concat",
      "ensuring",
      "filter",
      "fromIterable",
      "fromQueue",
      "map",
      "mapEffect",
      "toAsyncIterableEffect",
    ],
  },
] as const satisfies readonly AdoptedEffectRuntimeModuleExport[];

export const adoptedEffectTypeOnlyModules = [
  "effect/Crypto",
  "effect/Effect",
  "effect/FileSystem",
  "effect/Layer",
  "effect/ManagedRuntime",
  "effect/Path",
  "effect/Redacted",
  "effect/Schema",
] as const;
